name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: 187.127.106.95
        username: theteamguy
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /home/theteamguy
          git pull origin main
          npm run build
          pm2 restart theteamguy-api
